langage: cpp
dist: focal
compiler: g++

os:
 - linux

branches:
 only:
  - master
  


env:
 alias:
  - CONFIG=release

before_install:
- sudo add-apt-repository ppa:beineri/opt-qt-5.14.2-focal -y
- sudo apt-get update

install:
- sudo apt-get --yes install qt514-meta-full
- sudo apt-get --yes install libfontconfig1
- sudo apt-get --yes install mesa-common-dev
- sudo apt-get --yes install libglu1-mesa-dev

before_script:
- QTDIR="/opt/qt514"
- PATH="$QTDIR/bin:$PATH"
- source /opt/qt514/bin/qt514-env.sh
- ln -sf /usr/bin/x86_64-linux-gnu-ld.gold /usr/bin/ld

script:
- qmake
- make
