######################################################################
# Automatically generated by qmake (3.1) Wed Feb 12 12:00:25 2020
######################################################################

TEMPLATE = app
TARGET = fzNavigator
INCLUDEPATH += .
QT += widgets core webenginewidgets

# Input
SOURCES += main.cpp \
    Principalwind.cpp \
    webEngineTools.cpp

HEADERS += \
    Principalwind.h \
    webEngineTools.h
